spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportsvenue?characterEncoding=utf8&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: 127496
# 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置Mybatis需要绑定的文件路径
mybatis:
  typeAliasesPackage: com.graduation.sportsvenue.bean
  mapperLocations: classpath:mapper/*.xml
#配置端口
server:
  port: 8080
