package com.graduation.sportsvenue.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.order_no
     *
     * @mbggenerated
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.areaid
     *
     * @mbggenerated
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.startTime
     *
     * @mbggenerated
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.useTime
     *
     * @mbggenerated
     */
    private Integer usetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.payment
     *
     * @mbggenerated
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.paymentTime
     *
     * @mbggenerated
     */
    private Date paymenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.paystatus
     *
     * @mbggenerated
     */
    private Integer paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.id
     *
     * @return the value of order_v.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.id
     *
     * @param id the value for order_v.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.order_no
     *
     * @return the value of order_v.order_no
     *
     * @mbggenerated
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.order_no
     *
     * @param orderNo the value for order_v.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.userid
     *
     * @return the value of order_v.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.userid
     *
     * @param userid the value for order_v.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.areaid
     *
     * @return the value of order_v.areaid
     *
     * @mbggenerated
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.areaid
     *
     * @param areaid the value for order_v.areaid
     *
     * @mbggenerated
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.startTime
     *
     * @return the value of order_v.startTime
     *
     * @mbggenerated
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.startTime
     *
     * @param starttime the value for order_v.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.location
     *
     * @return the value of order_v.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.location
     *
     * @param location the value for order_v.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.price
     *
     * @return the value of order_v.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.price
     *
     * @param price the value for order_v.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.useTime
     *
     * @return the value of order_v.useTime
     *
     * @mbggenerated
     */
    public Integer getUsetime() {
        return usetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.useTime
     *
     * @param usetime the value for order_v.useTime
     *
     * @mbggenerated
     */
    public void setUsetime(Integer usetime) {
        this.usetime = usetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.payment
     *
     * @return the value of order_v.payment
     *
     * @mbggenerated
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.payment
     *
     * @param payment the value for order_v.payment
     *
     * @mbggenerated
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.paymentTime
     *
     * @return the value of order_v.paymentTime
     *
     * @mbggenerated
     */
    public Date getPaymenttime() {
        return paymenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.paymentTime
     *
     * @param paymenttime the value for order_v.paymentTime
     *
     * @mbggenerated
     */
    public void setPaymenttime(Date paymenttime) {
        this.paymenttime = paymenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.paystatus
     *
     * @return the value of order_v.paystatus
     *
     * @mbggenerated
     */
    public Integer getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.paystatus
     *
     * @param paystatus the value for order_v.paystatus
     *
     * @mbggenerated
     */
    public void setPaystatus(Integer paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.createTime
     *
     * @return the value of order_v.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.createTime
     *
     * @param createtime the value for order_v.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.updateTime
     *
     * @return the value of order_v.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_v.updateTime
     *
     * @param updatetime the value for order_v.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", orderNo=" + orderNo +
                ", userid=" + userid +
                ", areaid=" + areaid +
                ", starttime='" + starttime + '\'' +
                ", location='" + location + '\'' +
                ", price=" + price +
                ", usetime=" + usetime +
                ", payment=" + payment +
                ", paymenttime=" + paymenttime +
                ", paystatus=" + paystatus +
                ", createtime=" + createtime +
                ", updatetime=" + updatetime +
                '}';
    }
}