package com.graduation.sportsvenue.bean;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
@Data
public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.order_no
     *
     * @mbggenerated
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.areaid
     *
     * @mbggenerated
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.startTime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.useTime
     *
     * @mbggenerated
     */
    private Integer usetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.payment
     *
     * @mbggenerated
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.paymentTime
     *
     * @mbggenerated
     */
    private Date paymenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.paystatus
     *
     * @mbggenerated
     */
    private Integer paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_v.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_v.id
     *
     * @return the value of order_v.id
     *
     * @mbggenerated
     */

    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", orderNo=" + orderNo +
                ", userid=" + userid +
                ", areaid=" + areaid +
                ", starttime='" + starttime + '\'' +
                ", location='" + location + '\'' +
                ", price=" + price +
                ", usetime=" + usetime +
                ", payment=" + payment +
                ", paymenttime=" + paymenttime +
                ", paystatus=" + paystatus +
                ", createtime=" + createtime +
                ", updatetime=" + updatetime +
                '}';
    }
}